# LetsEncrypt tasks - facts.yml
---
- name: create facts.d directory
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: apply letsencrypt.fact template
  template:
    src: letsencrypt.fact.j2
    dest: "/etc/ansible/facts.d/{{ letsencrypt_fact_name }}.fact"
    mode: 0755
  register: update_facts

- name: check local facts
  setup:
    fact_path: /etc/ansible/facts.d
    filter: ansible_local*
  when: update_facts.changed
